// Generated by CoffeeScript 1.6.3
(function() {
  var en, extend, lingo, slug, word;

  lingo = require('lingo');

  extend = require('super');

  slug = require('slug');

  en = lingo.en;

  module.exports = word = extend({}, lingo);

  word.stripSlashes = function(str) {
    str = str.replace(/\\'/g, '\'');
    str = str.replace(/\\"/g, '"');
    str = str.replace(/\\0/g, '\0');
    return str = str.replace(/\\\\/g, '\\');
  };

  word.stripQuotes = function(str) {
    str = str.replace(/\'/g, '');
    return str = str.replace(/\"/g, '');
  };

  word.quotesEntities = function(str) {
    str = str.replace(/\'/g, '&#39;');
    return str = str.replace(/\"/g, '&quot;');
  };

  word.random = function(length) {
    var chars, i, random;
    chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
    random = '';
    i = 0;
    while (i < length) {
      random += chars.charAt(Math.floor(Math.random() * chars.length));
      i++;
    }
    return random;
  };

  word.repeat = function(str, times) {
    return new Array(times + 1).join(str);
  };

  word.censor = function(str, bad, replace) {
    var regExp, text, _i, _len;
    if (!Array.isArray(bad)) {
      bad = [bad];
    }
    for (_i = 0, _len = bad.length; _i < _len; _i++) {
      text = bad[_i];
      regExp = new RegExp('\\b' + text + '\\b', 'g');
      str = str.replace(regExp, replace);
    }
    return str;
  };

  word.stripLinks = function(str) {
    str = str.replace(/<a\s+[^>]+>/im, '');
    return str = str.replace(/<\/a>/im, '');
  };

  word.autoLink = function(str) {
    return str.replace(/((http|https|ftp):\/\/[\w?=&.\/-;#~%-]+(?![\w\s?&.\/;#~%"=-]*>))/g, '<a href="$1">$1</a>');
  };

  word.excerpt = function(str, length, ending) {
    if (ending == null) {
      ending = '...';
    }
    if (str.length <= length) {
      return str;
    }
    return str.substring(0, length) + ending;
  };

  word.limit = function(str, count) {
    var words;
    words = str.split(/\s+/g);
    if (words.length <= count) {
      return str;
    }
    return words.slice(0, count).join(' ');
  };

  word.wrap = function(str, width, br, cut) {
    var reg;
    if (br == null) {
      br = '\n';
    }
    if (cut == null) {
      cut = false;
    }
    reg = '.{1,' + width + '}(\\s|$)';
    if (cut === true) {
      return reg += '|.{' + width + '}|.+$';
    } else {
      reg += '|\\S+?(\\s|$)';
      return str.match(new RegExp(reg, 'g')).join(br);
    }
  };

  word.pluralize = function(count, singular, plural) {
    if (plural == null) {
      plural = null;
    }
    if (count === 1) {
      return singular;
    }
    if (!plural) {
      plural = en.pluralize(singular);
    }
    return plural;
  };

  word.join = function(words, last) {
    if (Array.isArray(words) === false) {
      words = words.split(/\s+/g);
    }
    return lingo.join(words, last);
  };

  word.slug = slug;

  module.exports.version = require('../package.json').version;

}).call(this);
